# Generated by Django 3.2.22 on 2023-10-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_cadastro',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info_cadastro',
            name='telefone_guardiao',
            field=models.IntegerField(),
        ),
    ]
