# Generated by Django 3.2.22 on 2023-10-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20231017_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_cadastro',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
