# Generated by Django 3.2.22 on 2023-10-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_info_cadastro_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_cadastro',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info_cadastro',
            name='email_guardiao',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
