# Generated by Django 3.2.22 on 2023-10-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20231017_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_cadastro',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
