# Generated by Django 3.2.22 on 2023-10-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_info_cadastro_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_cadastro',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info_cadastro',
            name='telefone_guardiao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
