# Generated by Django 3.2.22 on 2023-10-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_info_cadastro_nome_guardiao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info_cadastro',
        ),
    ]
