# Generated by Django 3.2.22 on 2023-10-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0009_delete_info_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=300)),
                ('bairro', models.CharField(max_length=50)),
                ('telefone', models.IntegerField()),
                ('nome_guardiao', models.CharField(max_length=200)),
                ('email_guardiao', models.EmailField(max_length=254)),
                ('telefone_guardiao', models.IntegerField()),
            ],
        ),
    ]
