# Generated by Django 3.2.22 on 2023-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_info_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_cadastro',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='info_cadastro',
            name='telefone_guardiao',
            field=models.CharField(max_length=15),
        ),
    ]
