# Generated by Django 3.2.22 on 2023-11-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20231018_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_cadastro',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
