# Generated by Django 3.2.22 on 2023-11-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='localdefala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codinome', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('relato', models.CharField(max_length=1000)),
            ],
        ),
    ]
