# Generated by Django 3.2.22 on 2023-11-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_localdefala'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='localdefala',
            new_name='relatos',
        ),
    ]
