# Generated by Django 3.2.22 on 2023-11-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_localdefala_relatos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='relatos',
            new_name='relato_fala',
        ),
    ]
